SELECT CAST([OM].[total_physical_memory_kb]/1024.00 AS NUMERIC(20,2)) AS [total_memory_mb]
       ,CAST([OM].[available_physical_memory_kb]/1024.00 AS NUMERIC(20,2)) AS [available_memory_mb]
       ,CAST([PM].[physical_memory_in_use_kb]/1024.00 AS NUMERIC(20,2)) AS [memory_usedby_sqlserver_mb]
       ,CAST((CAST([PM].[physical_memory_in_use_kb] AS NUMERIC(20,4))/[OM].[total_physical_memory_kb])*100 AS NUMERIC(5,2)) AS [memory_usedby_sqlserver_percent]
       ,(SELECT [value] FROM sys.configurations WHERE [name] = N'min server memory (MB)') AS [min_sqlserver_memory_mb]
       ,(SELECT [value] FROM sys.configurations WHERE [name] = N'max server memory (MB)') AS [max_sqlserver_memory_mb]
       ,(SELECT [cntr_value] FROM sys.dm_os_performance_counters WHERE [object_name] LIKE N'%:Buffer Manager%' AND [counter_name] = N'Page life expectancy') AS [page_life_expectancy]
       ,[PM].[process_physical_memory_low]
       ,[PM].[process_virtual_memory_low]
       ,[OM].[system_memory_state_desc]
FROM sys.dm_os_sys_memory [OM]
       CROSS APPLY sys.dm_os_process_memory [PM]
